lista_preguntas = [
    {"id":  1, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Pikachu", "respuesta_2": "Bulbasaur", "respuesta_3": "Charizard", "respuesta_4": "Ekans", "respuesta_correcta": 2},
    {"id":  2, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Clefable", "respuesta_2": "Wartortle", "respuesta_3": "Charmeleon", "respuesta_4": "Ivysaur", "respuesta_correcta": 4},
    {"id":  3, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Charizard", "respuesta_2": "Venusaur", "respuesta_3": "Raticate", "respuesta_4": "Nidoking", "respuesta_correcta": 2},
    {"id":  4, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Charmander", "respuesta_2": "Caterpie", "respuesta_3": "Pidgey", "respuesta_4": "Rattata", "respuesta_correcta": 1},
    {"id":  5, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Charizard", "respuesta_2": "Charmander", "respuesta_3": "Charmeleon", "respuesta_4": "Dragonite", "respuesta_correcta": 3},
    {"id":  6, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Charizard", "respuesta_2": "Rattata", "respuesta_3": "Raichu", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"id":  7, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Squirtle", "respuesta_2": "Meowth", "respuesta_3": "Raichu", "respuesta_4": "Ninguna", "respuesta_correcta": 1},
    {"id":  8, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Jigglypuff", "respuesta_2": "Wartortle", "respuesta_3": "Slowpoke", "respuesta_4": "Drowzee", "respuesta_correcta": 2},
    {"id":  9, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Squirtle", "respuesta_2": "Blastoise", "respuesta_3": "Bulbasaur", "respuesta_4": "Jigglypuff", "respuesta_correcta": 2},
    {"id": 10, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Wartortle", "respuesta_2": "Nidoking", "respuesta_3": "Raticate", "respuesta_4": "Caterpie", "respuesta_correcta": 4},
    {"id": 11, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Meowth", "respuesta_2": "Metapod", "respuesta_3": "Pidgeotto", "respuesta_4": "Ninetales", "respuesta_correcta": 2},
    {"id": 12, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Pidgeotto", "respuesta_2": "Charizard", "respuesta_3": "Butterfree", "respuesta_4": "Rhydon", "respuesta_correcta": 3},
    {"id": 13, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Weedle", "respuesta_2": "Mew", "respuesta_3": "Mr. Mime", "respuesta_4": "Kadabra", "respuesta_correcta": 1},
    {"id": 14, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Zapdos", "respuesta_2": "Kakuna", "respuesta_3": "Articuno", "respuesta_4": "Ekans", "respuesta_correcta": 2},
    {"id": 15, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Ditto", "respuesta_2": "Mewtwo", "respuesta_3": "Beedrill", "respuesta_4": "Gengar", "respuesta_correcta": 3},
    {"id": 16, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Pidgey", "respuesta_2": "Poliwrath", "respuesta_3": "Slowpoke", "respuesta_4": "Lapras", "respuesta_correcta": 1},
    {"id": 17, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Zapdos", "respuesta_2": "Mew", "respuesta_3": "Dragonite", "respuesta_4": "Pidgeotto", "respuesta_correcta": 4},
    {"id": 18, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Pidgeot", "respuesta_2": "Butterfree", "respuesta_3": "Jigglypuff", "respuesta_4": "Rhydon", "respuesta_correcta": 1},
    {"id": 19, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Rattata", "respuesta_2": "Gyarados", "respuesta_3": "Articuno", "respuesta_4": "Dragonite", "respuesta_correcta": 1},
    {"id": 20, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Charmander", "respuesta_2": "Raticate", "respuesta_3": "Pidgey", "respuesta_4": "Bulbasaur", "respuesta_correcta": 2},
    {"id": 21, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Mew", "respuesta_2": "Mewtwo", "respuesta_3": "Spearow", "respuesta_4": "Kakuna", "respuesta_correcta": 3},
    {"id": 22, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Fearow", "respuesta_2": "Psyduck", "respuesta_3": "Sandshrew", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"id": 23, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Butterfree", "respuesta_2": "Ekans", "respuesta_3": "Scyther", "respuesta_4": "Venonat", "respuesta_correcta": 2},
    {"id": 24, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Kadabra", "respuesta_2": "Machoke", "respuesta_3": "Arbok", "respuesta_4": "Hypno", "respuesta_correcta": 3},
    {"id": 25, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Pikachu", "respuesta_2": "Arbok", "respuesta_3": "Electrode", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"id": 26, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Pikachu", "respuesta_2": "Raticate", "respuesta_3": "Sandshrew", "respuesta_4": "Raichu", "respuesta_correcta": 4},
    {"id": 27, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Sandshrew", "respuesta_2": "Pikachu", "respuesta_3": "Bulbasaur", "respuesta_4": "Charmander", "respuesta_correcta": 1},
    {"id": 28, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Onix", "respuesta_2": "Slowbro", "respuesta_3": "Lapras", "respuesta_4": "Sandslash", "respuesta_correcta": 4},
    {"id": 29, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Nidoran", "respuesta_2": "Krabby", "respuesta_3": "Shellder", "respuesta_4": "Seadra", "respuesta_correcta": 1},
    {"id": 30, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Ponyta", "respuesta_2":"Rapidash","respuesta_3":"Nidorina","respuesta_4":"Dodrio","respuesta_correcta": 3},
    {"id": 31, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Nidoqueen", "respuesta_2": "Oddish", "respuesta_3": "Machamp", "respuesta_4": "Snorlax", "respuesta_correcta": 1},
    {"id": 32, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Bulbasaur", "respuesta_2": "Exeggcute", "respuesta_3": "Oddish", "respuesta_4": "Nidoran", "respuesta_correcta": 4},
    {"id": 33, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Nidorino", "respuesta_2": "Slowpoke", "respuesta_3": "Exeggcute", "respuesta_4": "Jynx", "respuesta_correcta": 1},
    {"id": 34, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Nidoking", "respuesta_2": "Machoke", "respuesta_3": "Cubone", "respuesta_4": "Ponyta", "respuesta_correcta": 1},
    {"id": 35, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Alakazam", "respuesta_2": "Clefairy", "respuesta_3": "Kadabra", "respuesta_4": "Slowpoke", "respuesta_correcta": 2},
    {"id": 36, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Cloyster", "respuesta_2": "Starmie", "respuesta_3": "Krabby", "respuesta_4": "Clefable", "respuesta_correcta": 4},
    {"id": 37, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Tangela", "respuesta_2": "Vulpix", "respuesta_3": "Scyther", "respuesta_4": "Paras", "respuesta_correcta": 2},
    {"id": 38, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Clefairy", "respuesta_2": "Jigglypuff", "respuesta_3": "Ninetales", "respuesta_4": "Kabuto", "respuesta_correcta": 3},
    {"id": 39, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Jigglypuff", "respuesta_2": "Cubone", "respuesta_3": "Slowbro", "respuesta_4": "Ponyta", "respuesta_correcta": 1},
    {"id": 40, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Exeggcute", "respuesta_2": "Chansey", "respuesta_3": "Wigglytuff", "respuesta_4": "Clefairy", "respuesta_correcta": 3},
    {"id": 41, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Dragonite", "respuesta_2": "Dragonaire", "respuesta_3": "Scyther", "respuesta_4": "Zubat", "respuesta_correcta": 4},
    {"id": 42, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Weedle", "respuesta_2": "Golbat", "respuesta_3": "Venonat", "respuesta_4": "Paras", "respuesta_correcta": 2},
    {"id": 43, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Oddish", "respuesta_2": "Omanyte", "respuesta_3": "Aerodactyl", "respuesta_4": "Lapras", "respuesta_correcta": 1},
    {"id": 44, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Gloom", "respuesta_2": "Seadra", "respuesta_3": "Starmie", "respuesta_4": "Shellder", "respuesta_correcta": 1},
    {"id": 45, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Doduo", "respuesta_2": "Fearow", "respuesta_3": "Vileplume", "respuesta_4": "Arcanine", "respuesta_correcta": 3},
    {"id": 46, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Gengar", "respuesta_2": "Paras", "respuesta_3": "Drowzee", "respuesta_4": "Haunter", "respuesta_correcta": 2},
    {"id": 47, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Vileplume", "respuesta_2": "Graveler", "respuesta_3": "Parasect", "respuesta_4": "Exeggcute", "respuesta_correcta": 3},
    {"id": 48, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Venonat", "respuesta_2": "Oddish", "respuesta_3": "Paras", "respuesta_4": "Vulpix", "respuesta_correcta": 1},
    {"id": 49, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Venomoth", "respuesta_2": "Fearow", "respuesta_3": "Zapdos", "respuesta_4": "Articuno", "respuesta_correcta": 1},
    {"id": 50, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Diglett", "respuesta_2": "Lapras", "respuesta_3": "Cloyster", "respuesta_4": "Dewgong", "respuesta_correcta": 1},
    {"id": 51, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Arcanine", "respuesta_2": "Dugtrio", "respuesta_3": "Ninetales", "respuesta_4": "Magmar", "respuesta_correcta": 2},
    {"id": 52, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Meowth", "respuesta_2": "Omanyte", "respuesta_3": "Slowbro", "respuesta_4": "Parasect", "respuesta_correcta": 1},
    {"id": 53, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Oddish", "respuesta_2": "Bellsprout", "respuesta_3": "Persian", "respuesta_4": "Drowzee", "respuesta_correcta": 3},
    {"id": 54, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Psyduck", "respuesta_2": "Diglett", "respuesta_3": "Fearow", "respuesta_4": "Dewgong", "respuesta_correcta": 1},
    {"id": 55, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Dragonite", "respuesta_2": "Gyarados", "respuesta_3": "Charizard", "respuesta_4": "Golduck", "respuesta_correcta": 4},
    {"id": 56, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Mankey", "respuesta_2": "Kabuto", "respuesta_3": "Aerodactyl", "respuesta_4": "Lapras", "respuesta_correcta": 1},
    {"id": 57, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Poliwrath", "respuesta_2": "Primeape", "respuesta_3": "Slowbro", "respuesta_4": "Kingler", "respuesta_correcta": 2},
    {"id": 58, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Machoke", "respuesta_2": "Machop", "respuesta_3": "Hitmonchan", "respuesta_4": "Growlithe", "respuesta_correcta": 4},
    {"id": 59, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Charizard", "respuesta_2": "Arcanine", "respuesta_3": "Magmar", "respuesta_4": "Arcanine", "respuesta_correcta": 4},
    {"id": 60, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Ditto", "respuesta_2": "Poliwag", "respuesta_3": "Mew", "respuesta_4": "Jynx", "respuesta_correcta": 2},
    {"id": 61, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Poliwhirl", "respuesta_2": "Arcanine", "respuesta_3": "Abra", "respuesta_4": "Psyduck", "respuesta_correcta": 1},
    {"id": 62, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Poliwrath", "respuesta_2": "Geodude", "respuesta_3": "Rhydon", "respuesta_4": "Onix", "respuesta_correcta": 1},
    {"id": 63, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Abra", "respuesta_2": "Oddish", "respuesta_3": "Gloom", "respuesta_4": "Venusaur", "respuesta_correcta": 1},
    {"id": 64, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Hitmonlee", "respuesta_2": "Machoke", "respuesta_3": "Kadabra", "respuesta_4": "Rhydon", "respuesta_correcta": 3},
    {"id": 65, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Electrode", "respuesta_2": "Weezing", "respuesta_3": "Alakazam", "respuesta_4": "Tentacruel", "respuesta_correcta": 3},
    {"id": 66, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Machop", "respuesta_2": "Weezing", "respuesta_3": "Koffing", "respuesta_4": "Muk", "respuesta_correcta": 1},
    {"id": 67, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Machoke", "respuesta_2": "Magnemite", "respuesta_3": "Electabuzz", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"id": 68, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Gengar", "respuesta_2": "Weezing", "respuesta_3": "MachMachampoke", "respuesta_4": "Jynx", "respuesta_correcta": 3},
    {"id": 69, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Articuno", "respuesta_2": "Bellsprout", "respuesta_3": "Dewgong", "respuesta_4": "Cloyster", "respuesta_correcta": 2},
    {"id": 70, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Geodude", "respuesta_2": "Onix", "respuesta_3": "Weepinbell", "respuesta_4": "Muk", "respuesta_correcta": 3},
    {"id": 71, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Victreebel", "respuesta_2": "Magnemite", "respuesta_3": "Electabuzz", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"id": 72, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Tentacool", "respuesta_2": "Charizard", "respuesta_3": "Flareon", "respuesta_4": "Arcanine", "respuesta_correcta": 1},
    {"id": 73, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Wartortle", "respuesta_2": "Tentacruel", "respuesta_3": "Golduck", "respuesta_4": "Seadra", "respuesta_correcta": 2},
    {"id": 74, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Geodude", "respuesta_2": "Graveler", "respuesta_3": "Rhyhorn", "respuesta_4": "Kabuto", "respuesta_correcta": 1},
    {"id": 75, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Chansey", "respuesta_2": "Exeggcute", "respuesta_3": "Golduck", "respuesta_4": "Graveler", "respuesta_correcta": 4},
    {"id": 76, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Alakazam", "respuesta_2": "Mr. Mime", "respuesta_3": "Hypno", "respuesta_4": "Golem", "respuesta_correcta": 4},
    {"id": 77, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Dragonite", "respuesta_2": "Articuno", "respuesta_3": "Ponyta", "respuesta_4": "Mewtwo", "respuesta_correcta": 3},
    {"id": 78, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Shellder", "respuesta_2": "Rapidash", "respuesta_3": "Omanyte", "respuesta_4": "Kabutops", "respuesta_correcta": 2},
    {"id": 79, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Slowpoke", "respuesta_2": "Ninetales", "respuesta_3": "Flareon", "respuesta_4": "Rapidash", "respuesta_correcta": 1},
    {"id": 80, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Pikachu", "respuesta_2": "Slowbro", "respuesta_3": "Magnemite", "respuesta_4": "Jolteon", "respuesta_correcta": 2},
    {"id": 81, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Ekans", "respuesta_2": "Koffing", "respuesta_3": "Nidoran", "respuesta_4": "Magnemite", "respuesta_correcta": 4},
    {"id": 82, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Pidgeotto", "respuesta_2": "Fearow", "respuesta_3": "Dodrio", "respuesta_4": "Magneton", "respuesta_correcta": 4},
    {"id": 83, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Clefairy", "respuesta_2": "Wigglytuff", "respuesta_3": "Magneton", "respuesta_4": "Farfetch'd", "respuesta_correcta": 4},
    {"id": 84, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Cubone", "respuesta_2": "Doduo", "respuesta_3": "Diglett", "respuesta_4": "Dugtrio", "respuesta_correcta": 2},
    {"id": 85, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Dodrio", "respuesta_2": "Psyduck", "respuesta_3": "Golduck", "respuesta_4": "Poliwag", "respuesta_correcta": 1},
    {"id": 86, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Kadabra", "respuesta_2": "Machoke", "respuesta_3": "Graveler", "respuesta_4": "Seel", "respuesta_correcta": 4},
    {"id": 87, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Dewgong", "respuesta_2": "Mr. Mime", "respuesta_3": "Exeggutor", "respuesta_4": "Clefairy", "respuesta_correcta": 1},
    {"id": 88, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Caterpie", "respuesta_2": "Weedle", "respuesta_3": "Grimer", "respuesta_4": "Beedrill", "respuesta_correcta": 3},
    {"id": 89, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Dodrio", "respuesta_2": "Exeggutor", "respuesta_3": "Muk", "respuesta_4": "Machoke", "respuesta_correcta": 3},
    {"id": 90, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Zapdos", "respuesta_2": "Shellder", "respuesta_3": "Moltres", "respuesta_4": "Lapras", "respuesta_correcta": 2},
    {"id": 91, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Zubat", "respuesta_2": "Golbat", "respuesta_3": "Cloyster", "respuesta_4": "Grimer", "respuesta_correcta": 3},
    {"id": 92, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Jolteon", "respuesta_2": "Zapdos", "respuesta_3": "Pikachu", "respuesta_4": "Gastly", "respuesta_correcta": 4},
    {"id": 93, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Charmander", "respuesta_2": "Poliwag", "respuesta_3": "Abra", "respuesta_4": "Haunter", "respuesta_correcta": 4},
    {"id": 94, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Ditto", "respuesta_2": "Kadabra", "respuesta_3": "Pikachu", "respuesta_4": "Gengar", "respuesta_correcta": 4},
    {"id": 95, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Jigglypuff", "respuesta_2": "Nidorina", "respuesta_3": "Clefairy", "respuesta_4": "Onix", "respuesta_correcta": 4},
    {"id": 96, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Drowzee", "respuesta_2": "Psyduck", "respuesta_3": "Seel", "respuesta_4": "Poliwag", "respuesta_correcta": 1},
    {"id": 97, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Caterpie", "respuesta_2": "Weedle", "respuesta_3": "Paras", "respuesta_4": "Hypno", "respuesta_correcta": 4},
    {"id": 98, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Flareon", "respuesta_2": "Rapidash", "respuesta_3": "Krabby", "respuesta_4": "Magmar", "respuesta_correcta": 3},
    {"id": 99, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Nidorino", "respuesta_2": "Haunter", "respuesta_3": "Kingler", "respuesta_4": "Hypno", "respuesta_correcta": 3},
    {"id":100, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Articuno", "respuesta_2": "Voltorb", "respuesta_3": "Lapras", "respuesta_4": "Jynx", "respuesta_correcta": 2},
    {"id":101, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Dragonair", "respuesta_2": "Dragonite", "respuesta_3": "Gyarados", "respuesta_4": "Electrode", "respuesta_correcta": 4},
    {"id":102, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Omanyte", "respuesta_2": "Kabuto", "respuesta_3": "Exeggcute", "respuesta_4": "Gyarados", "respuesta_correcta": 3},
    {"id":103, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Bulbasaur", "respuesta_2": "Gloom", "respuesta_3": "Exeggutor", "respuesta_4": "Bellosom", "respuesta_correcta": 3},
    {"id":104, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Pikachu", "respuesta_2": "Electrode", "respuesta_3": "Magnemite", "respuesta_4": "Cubone", "respuesta_correcta": 4},
    {"id":105, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Clefairy", "respuesta_2": "Eevee", "respuesta_3": "Jigglypuff", "respuesta_4": "Marowak", "respuesta_correcta": 4},
    {"id":106, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Gastly", "respuesta_2": "Haunter", "respuesta_3": "Gengar", "respuesta_4": "Hitmonlee", "respuesta_correcta": 4},
    {"id":107, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Voltorb", "respuesta_2": "Electrode", "respuesta_3": "Hitmonchan", "respuesta_4": "Hitmonlee", "respuesta_correcta": 3},
    {"id":108, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Lickitung", "respuesta_2": "Tauros", "respuesta_3": "Primeape", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"id":109, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Jolteon", "respuesta_2": "Koffing", "respuesta_3": "Aerodactyl", "respuesta_4": "Mewtwo", "respuesta_correcta": 2},
    {"id":110, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Squirtle", "respuesta_2": "Horsea", "respuesta_3": "Seadra", "respuesta_4": "Weezing", "respuesta_correcta": 4},
    {"id":111, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Oddish", "respuesta_2": "Bellsprout", "respuesta_3": "Vileplume", "respuesta_4": "Rhyhorn", "respuesta_correcta": 4},
    {"id":112, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Mewtwo", "respuesta_2": "Rhydon", "respuesta_3": "Articuno", "respuesta_4": "Gyarados", "respuesta_correcta": 2},
    {"id":113, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Farfetch'd", "respuesta_2": "Golduck", "respuesta_3": "Psyduck", "respuesta_4": "Chansey", "respuesta_correcta": 4},
    {"id":114, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Tangela", "respuesta_2": "Poliwrath", "respuesta_3": "Bellsprout", "respuesta_4": "Rhyhorn", "respuesta_correcta": 1},
    {"id":115, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Vaporeon", "respuesta_2": "Lapras", "respuesta_3": "Omanyte", "respuesta_4": "Kangaskhan", "respuesta_correcta": 4},
    {"id":116, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Magnemite", "respuesta_2": "Magneton", "respuesta_3": "Horsea", "respuesta_4": "Staryu", "respuesta_correcta": 3},
    {"id":117, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Ditto", "respuesta_2": "Grimer", "respuesta_3": "Magmar", "respuesta_4": "Seadra", "respuesta_correcta": 4},
    {"id":118, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Grimer", "respuesta_2": "Goldeen", "respuesta_3": "Koffing", "respuesta_4": "Muk", "respuesta_correcta": 2},
    {"id":119, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Dragonite", "respuesta_2": "Seaking", "respuesta_3": "Rhydon", "respuesta_4": "Machamp", "respuesta_correcta": 2},
    {"id":120, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Eevee", "respuesta_2": "Pikachu", "respuesta_3": "Staryu", "respuesta_4": "Grimer", "respuesta_correcta": 3},
    {"id":121, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Charizard", "respuesta_2": "Rapidash", "respuesta_3": "Magmar", "respuesta_4": "Starmie", "respuesta_correcta": 4},
    {"id":122, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Mr. Mime", "respuesta_2": "Kabutops", "respuesta_3": "Omastar", "respuesta_4": "Rapidash", "respuesta_correcta": 1},
    {"id":123, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Grimer", "respuesta_2": "Muk", "respuesta_3": "Scyther", "respuesta_4": "Electrode", "respuesta_correcta": 3},
    {"id":124, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Jynx", "respuesta_2": "Gastly", "respuesta_3": "Eevee", "respuesta_4": "Pikachu", "respuesta_correcta": 1},
    {"id":125, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Gastly", "respuesta_2": "Haunter", "respuesta_3": "Electabuzz", "respuesta_4": "Cubone", "respuesta_correcta": 3},
    {"id":126, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Horsea", "respuesta_2": "Magikarp", "respuesta_3": "Shellder", "respuesta_4": "Magmar", "respuesta_correcta": 4},
    {"id":127, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Growlithe", "respuesta_2": "Vulpix", "respuesta_3": "Pinsir", "respuesta_4": "Shellder", "respuesta_correcta": 3},
    {"id":128, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Tauros", "respuesta_2": "Golem", "respuesta_3": "Onix", "respuesta_4": "Lapras", "respuesta_correcta": 1},
    {"id":129, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Electrode", "respuesta_2": "Voltorb", "respuesta_3": "Magikarp", "respuesta_4": "Lapras", "respuesta_correcta": 3},
    {"id":130, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Lickitung", "respuesta_2": "Slowpoke", "respuesta_3": "Hypno", "respuesta_4": "Gyarados", "respuesta_correcta": 4},
    {"id":131, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Lapras", "respuesta_2": "Geodude", "respuesta_3": "Rhyhorn", "respuesta_4": "Tauros", "respuesta_correcta": 1},
    {"id":132, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Ditto", "respuesta_2": "Ivysaur", "respuesta_3": "Vileplume", "respuesta_4": "Exeggutor", "respuesta_correcta": 1},
    {"id":133, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Zubat", "respuesta_2": "Eevee", "respuesta_3": "Magnemite", "respuesta_4": "Onix", "respuesta_correcta": 2},
    {"id":134, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Vaporeon", "respuesta_2": "Charmander", "respuesta_3": "Squirtle", "respuesta_4": "Pidgey", "respuesta_correcta": 1},
    {"id":135, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Jolteon", "respuesta_2": "Poliwag", "respuesta_3": "Shellder", "respuesta_4": "Magikarp", "respuesta_correcta": 1},
    {"id":136, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Kabuto", "respuesta_2": "Flareon", "respuesta_3": "Paras", "respuesta_4": "Omanyte", "respuesta_correcta": 2},
    {"id":137, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Porygon", "respuesta_2": "Electrode", "respuesta_3": "Magnemite", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"id":138, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Vulpix", "respuesta_2": "Charizard", "respuesta_3": "Magmar", "respuesta_4": "Omanyte", "respuesta_correcta": 4},
    {"id":139, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Omastar", "respuesta_2": "Squirtle", "respuesta_3": "Seadra", "respuesta_4": "Psyduck", "respuesta_correcta": 1},
    {"id":140, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Kabuto", "respuesta_2": "Magikarp", "respuesta_3": "Lapras", "respuesta_4": "Omanyte", "respuesta_correcta": 1},
    {"id":141, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Kabutops", "respuesta_2": "Articuno", "respuesta_3": "Pidgeot", "respuesta_4": "Zapdos", "respuesta_correcta": 1},
    {"id":142, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Aerodactyl", "respuesta_2": "Pikachu", "respuesta_3": "Rhydon", "respuesta_4": "Magikarp", "respuesta_correcta": 1},
    {"id":143, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Jigglypuff", "respuesta_2": "Squirtle", "respuesta_3": "Zubat", "respuesta_4": "Snorlax", "respuesta_correcta": 4},
    {"id":144, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Squirtle", "respuesta_2": "Articuno", "respuesta_3": "Aerodactyl", "respuesta_4": "Omanyte", "respuesta_correcta": 2},
    {"id":145, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Zapdos", "respuesta_2": "Abra", "respuesta_3": "Kadabra", "respuesta_4": "Pikachu", "respuesta_correcta": 1},
    {"id":146, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Mewtwo", "respuesta_2": "Abra", "respuesta_3": "Psyduck", "respuesta_4": "Moltres", "respuesta_correcta": 4},
    {"id":147, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Dratini", "respuesta_2": "Pidgeot", "respuesta_3": "Articuno", "respuesta_4": "Aerodactyl", "respuesta_correcta": 1},
    {"id":148, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Kabuto", "respuesta_2": "Magikarp", "respuesta_3": "Onix", "respuesta_4": "Dragonair", "respuesta_correcta": 4},
    {"id":149, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Dragonite", "respuesta_2": "Exeggutor", "respuesta_3": "Pidgey", "respuesta_4": "Bulbasaur", "respuesta_correcta": 1},
    {"id":150, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Magikarp", "respuesta_2": "Mewtwo", "respuesta_3": "Dragonite", "respuesta_4": "Zubat", "respuesta_correcta": 2},
    {"id":151, "pregunta": "¿Quién es ese Pokémon?", "respuesta_1": "Mew", "respuesta_2": "Rhyhorn", "respuesta_3": "Geodude", "respuesta_4": "Nidoran", "respuesta_correcta": 1}
]