import pygame

pygame.init()

# Pantalla
ANCHO = 800
ALTO = 600
VENTANA = (ANCHO,ALTO)
FPS = 60

# Dificultades
# Normal
CANTIDAD_VIDAS_NORMAL = 3
PUNTUACION_ACIERTO_NORMAL = 100
PUNTUACION_ERROR_NORMAL = 50

# Fácil
CANTIDAD_VIDAS_FACIL = 5
PUNTUACION_ACIERTO_FACIL = 100
PUNTUACION_ERROR_FACIL = 25

# Difícil
CANTIDAD_VIDAS_DIFICIL = 1
PUNTUACION_ACIERTO_DIFICIL = 100
PUNTUACION_ERROR_DIFICIL = 100