preguntas = [
    {"pregunta": "¿Cuál es el primer Pokémon de la Pokédex?", "respuesta_1": "Pikachu", "respuesta_2": "Bulbasaur", "respuesta_3": "Charizard", "respuesta_4": "Ekans", "respuesta_correcta": 2},
    {"pregunta": "¿De qué tipo es Snorlax?", "respuesta_1": "Fuego", "respuesta_2": "Fantasma", "respuesta_3": "Lucha", "respuesta_4": "Normal", "respuesta_correcta": 4},
    {"pregunta": "¿Cuál es la evolución de Charmander?", "respuesta_1": "Charizard", "respuesta_2": "Charmeleon", "respuesta_3": "Charmy", "respuesta_4": "Charjabug", "respuesta_correcta": 2},
    {"pregunta": "¿Qué tipo tiene Pikachu?", "respuesta_1": "Eléctrico", "respuesta_2": "Agua", "respuesta_3": "Volador", "respuesta_4": "Normal", "respuesta_correcta": 1},
    {"pregunta": "¿Cuántas evoluciones tiene Eevee en la primera generación?", "respuesta_1": "Dos", "respuesta_2": "Cuatro", "respuesta_3": "Tres", "respuesta_4": "Cinco", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Ratón eléctrico'?", "respuesta_1": "Pikachu", "respuesta_2": "Rattata", "respuesta_3": "Raichu", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la evolución de Meowth?", "respuesta_1": "Persian", "respuesta_2": "Alolan Meowth", "respuesta_3": "Raichu", "respuesta_4": "Ninguna", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido por dormir casi todo el día?", "respuesta_1": "Jigglypuff", "respuesta_2": "Snorlax", "respuesta_3": "Slowpoke", "respuesta_4": "Drowzee", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo fuego?", "respuesta_1": "Squirtle", "respuesta_2": "Charmander", "respuesta_3": "Bulbasaur", "respuesta_4": "Jigglypuff", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es el movimiento característico de Jigglypuff?", "respuesta_1": "Canto", "respuesta_2": "Impactrueno", "respuesta_3": "Látigo", "respuesta_4": "Confusión", "respuesta_correcta": 1},
    {"pregunta": "¿De qué tipo es el Pokémon Gyarados?", "respuesta_1": "Agua y Eléctrico", "respuesta_2": "Agua y Volador", "respuesta_3": "Agua y Dragón", "respuesta_4": "Solo Agua", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál de estos Pokémon no es de la primera generación?", "respuesta_1": "Pidgeotto", "respuesta_2": "Charizard", "respuesta_3": "Togepi", "respuesta_4": "Rhydon", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon tiene la habilidad de transformarse en otros?", "respuesta_1": "Ditto", "respuesta_2": "Mew", "respuesta_3": "Mr. Mime", "respuesta_4": "Kadabra", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es el Pokémon legendario de tipo fuego?", "respuesta_1": "Zapdos", "respuesta_2": "Moltres", "respuesta_3": "Articuno", "respuesta_4": "Ho-oh", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon es conocido como el clon de Mew?", "respuesta_1": "Ditto", "respuesta_2": "Zapdos", "respuesta_3": "Mewtwo", "respuesta_4": "Gengar", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es la evolución de Poliwag?", "respuesta_1": "Poliwhirl", "respuesta_2": "Poliwrath", "respuesta_3": "Slowpoke", "respuesta_4": "Lapras", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon tiene la Pokédex como número 150?", "respuesta_1": "Mewtwo", "respuesta_2": "Mew", "respuesta_3": "Dragonite", "respuesta_4": "Snorlax", "respuesta_correcta": 1},
    {"pregunta": "¿De qué tipo es Onix?", "respuesta_1": "Roca y Tierra", "respuesta_2": "Roca y Acero", "respuesta_3": "Tierra y Veneno", "respuesta_4": "Solo Tierra", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el Rey de los Mares?", "respuesta_1": "Lapras", "respuesta_2": "Gyarados", "respuesta_3": "Articuno", "respuesta_4": "Dragonite", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es el Pokémon inicial de agua?", "respuesta_1": "Charmander", "respuesta_2": "Squirtle", "respuesta_3": "Pidgey", "respuesta_4": "Bulbasaur", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon tiene el número 151 en la Pokédex?", "respuesta_1": "Mew", "respuesta_2": "Mewtwo", "respuesta_3": "Dragonite", "respuesta_4": "Zapdos", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo Planta?", "respuesta_1": "Oddish", "respuesta_2": "Psyduck", "respuesta_3": "Sandshrew", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon abeja'?", "respuesta_1": "Butterfree", "respuesta_2": "Beedrill", "respuesta_3": "Scyther", "respuesta_4": "Venonat", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es la evolución final de Abra?", "respuesta_1": "Kadabra", "respuesta_2": "Machoke", "respuesta_3": "Alakazam", "respuesta_4": "Hypno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon evoluciona en Raichu?", "respuesta_1": "Pikachu", "respuesta_2": "Pichu", "respuesta_3": "Electrode", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"pregunta": "¿De qué tipo es el Pokémon Dragonite?", "respuesta_1": "Dragón y Volador", "respuesta_2": "Agua y Volador", "respuesta_3": "Normal", "respuesta_4": "Solo Dragón", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon tiene el número 25 en la Pokédex?", "respuesta_1": "Raichu", "respuesta_2": "Pikachu", "respuesta_3": "Bulbasaur", "respuesta_4": "Charmander", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo roca?", "respuesta_1": "Onix", "respuesta_2": "Slowbro", "respuesta_3": "Lapras", "respuesta_4": "Magmar", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon evoluciona en Gyarados?", "respuesta_1": "Magikarp", "respuesta_2": "Krabby", "respuesta_3": "Shellder", "respuesta_4": "Seadra", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon caballo'?","respuesta_1":"Ponyta","respuesta_2":"Rapidash","respuesta_3":"Tauros","respuesta_4":"Dodrio","respuesta_correcta": 1},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo eléctrico?", "respuesta_1": "Magnemite", "respuesta_2": "Oddish", "respuesta_3": "Machamp", "respuesta_4": "Snorlax", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon semilla'?", "respuesta_1": "Bulbasaur", "respuesta_2": "Exeggcute", "respuesta_3": "Oddish", "respuesta_4": "Tangela", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon de tipo psíquico tiene tres evoluciones?", "respuesta_1": "Abra", "respuesta_2": "Slowpoke", "respuesta_3": "Exeggcute", "respuesta_4": "Jynx", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo veneno?", "respuesta_1": "Ekans", "respuesta_2": "Machoke", "respuesta_3": "Cubone", "respuesta_4": "Ponyta", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon psíquico'?", "respuesta_1": "Alakazam", "respuesta_2": "Hypno", "respuesta_3": "Kadabra", "respuesta_4": "Slowpoke", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es la evolución de Shellder?", "respuesta_1": "Cloyster", "respuesta_2": "Starmie", "respuesta_3": "Krabby", "respuesta_4": "Omastar", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido por lanzar hojas afiladas?", "respuesta_1": "Tangela", "respuesta_2": "Exeggutor", "respuesta_3": "Scyther", "respuesta_4": "Paras", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon evoluciona usando una piedra lunar?", "respuesta_1": "Clefairy", "respuesta_2": "Jigglypuff", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿De qué tipo es Voltorb?", "respuesta_1": "Eléctrico", "respuesta_2": "Veneno", "respuesta_3": "Normal", "respuesta_4": "Roca", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon huevo'?", "respuesta_1": "Exeggcute", "respuesta_2": "Chansey", "respuesta_3": "Togepi", "respuesta_4": "Clefairy", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la evolución final de Dratini?", "respuesta_1": "Dragonite", "respuesta_2": "Dragonaire", "respuesta_3": "Dracosaur", "respuesta_4": "Rayquaza", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon se transforma en Butterfree?", "respuesta_1": "Weedle", "respuesta_2": "Caterpie", "respuesta_3": "Venonat", "respuesta_4": "Paras", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon es el fósil de la Cúpula?", "respuesta_1": "Kabuto", "respuesta_2": "Omanyte", "respuesta_3": "Aerodactyl", "respuesta_4": "Lapras", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la evolución de Krabby?", "respuesta_1": "Kingler", "respuesta_2": "Seadra", "respuesta_3": "Starmie", "respuesta_4": "Shellder", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon puede aprender el ataque Vuelo?", "respuesta_1": "Doduo", "respuesta_2": "Fearow", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es conocido por causar pesadillas?", "respuesta_1": "Gengar", "respuesta_2": "Hypno", "respuesta_3": "Drowzee", "respuesta_4": "Haunter", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál de estos Pokémon es una evolución por intercambio?", "respuesta_1": "Machoke", "respuesta_2": "Graveler", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿De qué tipo es Hitmonchan?", "respuesta_1": "Lucha", "respuesta_2": "Normal", "respuesta_3": "Tierra", "respuesta_4": "Veneno", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon ave'?", "respuesta_1": "Pidgey", "respuesta_2": "Fearow", "respuesta_3": "Zapdos", "respuesta_4": "Articuno", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon de tipo hielo es legendario?", "respuesta_1": "Articuno", "respuesta_2": "Lapras", "respuesta_3": "Cloyster", "respuesta_4": "Dewgong", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la evolución de Growlithe?", "respuesta_1": "Arcanine", "respuesta_2": "Rapidash", "respuesta_3": "Ninetales", "respuesta_4": "Magmar", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon tiene la habilidad de regenerar sus patas?", "respuesta_1": "Kabutops", "respuesta_2": "Omanyte", "respuesta_3": "Slowbro", "respuesta_4": "Parasect", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon planta'?", "respuesta_1": "Oddish", "respuesta_2": "Bellsprout", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿De qué tipo es Lapras?", "respuesta_1": "Agua y Hielo", "respuesta_2": "Solo Agua", "respuesta_3": "Agua y Dragón", "respuesta_4": "Agua y Normal", "respuesta_correcta": 1}
]

