preguntas = [
    {"pregunta": "¿Cuál es el primer Pokémon de la Pokédex?", "respuesta_1": "Pikachu", "respuesta_2": "Bulbasaur", "respuesta_3": "Charizard", "respuesta_4": "Ekans", "respuesta_correcta": 2},
    {"pregunta": "¿De qué tipo es Snorlax?", "respuesta_1": "Fuego", "respuesta_2": "Fantasma", "respuesta_3": "Lucha", "respuesta_4": "Normal", "respuesta_correcta": 4},
    {"pregunta": "¿Cuál es la evolución de Charmander?", "respuesta_1": "Charizard", "respuesta_2": "Charmeleon", "respuesta_3": "Charmy", "respuesta_4": "Charjabug", "respuesta_correcta": 2},
    {"pregunta": "¿Qué tipo tiene Pikachu?", "respuesta_1": "Eléctrico", "respuesta_2": "Agua", "respuesta_3": "Volador", "respuesta_4": "Normal", "respuesta_correcta": 1},
    {"pregunta": "¿Cuántas evoluciones tiene Eevee en la primera generación?", "respuesta_1": "Dos", "respuesta_2": "Cuatro", "respuesta_3": "Tres", "respuesta_4": "Cinco", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Ratón eléctrico'?", "respuesta_1": "Pikachu", "respuesta_2": "Rattata", "respuesta_3": "Raichu", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la evolución de Meowth?", "respuesta_1": "Persian", "respuesta_2": "Alolan Meowth", "respuesta_3": "Raichu", "respuesta_4": "Ninguna", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido por dormir casi todo el día?", "respuesta_1": "Jigglypuff", "respuesta_2": "Snorlax", "respuesta_3": "Slowpoke", "respuesta_4": "Drowzee", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo fuego?", "respuesta_1": "Squirtle", "respuesta_2": "Charmander", "respuesta_3": "Bulbasaur", "respuesta_4": "Jigglypuff", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es el movimiento característico de Jigglypuff?", "respuesta_1": "Canto", "respuesta_2": "Impactrueno", "respuesta_3": "Látigo", "respuesta_4": "Confusión", "respuesta_correcta": 1},
    {"pregunta": "¿De qué tipo es el Pokémon Gyarados?", "respuesta_1": "Agua y Eléctrico", "respuesta_2": "Agua y Volador", "respuesta_3": "Agua y Dragón", "respuesta_4": "Solo Agua", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál de estos Pokémon no es de la primera generación?", "respuesta_1": "Pidgeotto", "respuesta_2": "Charizard", "respuesta_3": "Togepi", "respuesta_4": "Rhydon", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon tiene la habilidad de transformarse en otros?", "respuesta_1": "Ditto", "respuesta_2": "Mew", "respuesta_3": "Mr. Mime", "respuesta_4": "Kadabra", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es el Pokémon legendario de tipo fuego?", "respuesta_1": "Zapdos", "respuesta_2": "Moltres", "respuesta_3": "Articuno", "respuesta_4": "Ho-oh", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon es conocido como el clon de Mew?", "respuesta_1": "Ditto", "respuesta_2": "Zapdos", "respuesta_3": "Mewtwo", "respuesta_4": "Gengar", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es la evolución de Poliwag?", "respuesta_1": "Poliwhirl", "respuesta_2": "Poliwrath", "respuesta_3": "Slowpoke", "respuesta_4": "Lapras", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon tiene la Pokédex como número 150?", "respuesta_1": "Mewtwo", "respuesta_2": "Mew", "respuesta_3": "Dragonite", "respuesta_4": "Snorlax", "respuesta_correcta": 1},
    {"pregunta": "¿De qué tipo es Onix?", "respuesta_1": "Roca y Tierra", "respuesta_2": "Roca y Acero", "respuesta_3": "Tierra y Veneno", "respuesta_4": "Solo Tierra", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el Rey de los Mares?", "respuesta_1": "Lapras", "respuesta_2": "Gyarados", "respuesta_3": "Articuno", "respuesta_4": "Dragonite", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es el Pokémon inicial de agua?", "respuesta_1": "Charmander", "respuesta_2": "Squirtle", "respuesta_3": "Pidgey", "respuesta_4": "Bulbasaur", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon tiene el número 151 en la Pokédex?", "respuesta_1": "Mew", "respuesta_2": "Mewtwo", "respuesta_3": "Dragonite", "respuesta_4": "Zapdos", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo Planta?", "respuesta_1": "Oddish", "respuesta_2": "Psyduck", "respuesta_3": "Sandshrew", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon abeja'?", "respuesta_1": "Butterfree", "respuesta_2": "Beedrill", "respuesta_3": "Scyther", "respuesta_4": "Venonat", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es la evolución final de Abra?", "respuesta_1": "Kadabra", "respuesta_2": "Machoke", "respuesta_3": "Alakazam", "respuesta_4": "Hypno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon evoluciona en Raichu?", "respuesta_1": "Pikachu", "respuesta_2": "Pichu", "respuesta_3": "Electrode", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"pregunta": "¿De qué tipo es el Pokémon Dragonite?", "respuesta_1": "Dragón y Volador", "respuesta_2": "Agua y Volador", "respuesta_3": "Normal", "respuesta_4": "Solo Dragón", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon tiene el número 25 en la Pokédex?", "respuesta_1": "Raichu", "respuesta_2": "Pikachu", "respuesta_3": "Bulbasaur", "respuesta_4": "Charmander", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo roca?", "respuesta_1": "Onix", "respuesta_2": "Slowbro", "respuesta_3": "Lapras", "respuesta_4": "Magmar", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon evoluciona en Gyarados?", "respuesta_1": "Magikarp", "respuesta_2": "Krabby", "respuesta_3": "Shellder", "respuesta_4": "Seadra", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon caballo'?","respuesta_1":"Ponyta","respuesta_2":"Rapidash","respuesta_3":"Tauros","respuesta_4":"Dodrio","respuesta_correcta": 1},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo eléctrico?", "respuesta_1": "Magnemite", "respuesta_2": "Oddish", "respuesta_3": "Machamp", "respuesta_4": "Snorlax", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon semilla'?", "respuesta_1": "Bulbasaur", "respuesta_2": "Exeggcute", "respuesta_3": "Oddish", "respuesta_4": "Tangela", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon de tipo psíquico tiene tres evoluciones?", "respuesta_1": "Abra", "respuesta_2": "Slowpoke", "respuesta_3": "Exeggcute", "respuesta_4": "Jynx", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo veneno?", "respuesta_1": "Ekans", "respuesta_2": "Machoke", "respuesta_3": "Cubone", "respuesta_4": "Ponyta", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon psíquico'?", "respuesta_1": "Alakazam", "respuesta_2": "Hypno", "respuesta_3": "Kadabra", "respuesta_4": "Slowpoke", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es la evolución de Shellder?", "respuesta_1": "Cloyster", "respuesta_2": "Starmie", "respuesta_3": "Krabby", "respuesta_4": "Omastar", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido por lanzar hojas afiladas?", "respuesta_1": "Tangela", "respuesta_2": "Exeggutor", "respuesta_3": "Scyther", "respuesta_4": "Paras", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon evoluciona usando una piedra lunar?", "respuesta_1": "Clefairy", "respuesta_2": "Jigglypuff", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿De qué tipo es Voltorb?", "respuesta_1": "Eléctrico", "respuesta_2": "Veneno", "respuesta_3": "Normal", "respuesta_4": "Roca", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon huevo'?", "respuesta_1": "Exeggcute", "respuesta_2": "Chansey", "respuesta_3": "Togepi", "respuesta_4": "Clefairy", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la evolución final de Dratini?", "respuesta_1": "Dragonite", "respuesta_2": "Dragonaire", "respuesta_3": "Dracosaur", "respuesta_4": "Rayquaza", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon se transforma en Butterfree?", "respuesta_1": "Weedle", "respuesta_2": "Caterpie", "respuesta_3": "Venonat", "respuesta_4": "Paras", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon es el fósil de la Cúpula?", "respuesta_1": "Kabuto", "respuesta_2": "Omanyte", "respuesta_3": "Aerodactyl", "respuesta_4": "Lapras", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la evolución de Krabby?", "respuesta_1": "Kingler", "respuesta_2": "Seadra", "respuesta_3": "Starmie", "respuesta_4": "Shellder", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon puede aprender el ataque Vuelo?", "respuesta_1": "Doduo", "respuesta_2": "Fearow", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es conocido por causar pesadillas?", "respuesta_1": "Gengar", "respuesta_2": "Hypno", "respuesta_3": "Drowzee", "respuesta_4": "Haunter", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál de estos Pokémon es una evolución por intercambio?", "respuesta_1": "Machoke", "respuesta_2": "Graveler", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿De qué tipo es Hitmonchan?", "respuesta_1": "Lucha", "respuesta_2": "Normal", "respuesta_3": "Tierra", "respuesta_4": "Veneno", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon ave'?", "respuesta_1": "Pidgey", "respuesta_2": "Fearow", "respuesta_3": "Zapdos", "respuesta_4": "Articuno", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon de tipo hielo es legendario?", "respuesta_1": "Articuno", "respuesta_2": "Lapras", "respuesta_3": "Cloyster", "respuesta_4": "Dewgong", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la evolución de Growlithe?", "respuesta_1": "Arcanine", "respuesta_2": "Rapidash", "respuesta_3": "Ninetales", "respuesta_4": "Magmar", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon tiene la habilidad de regenerar sus patas?", "respuesta_1": "Kabutops", "respuesta_2": "Omanyte", "respuesta_3": "Slowbro", "respuesta_4": "Parasect", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon planta'?", "respuesta_1": "Oddish", "respuesta_2": "Bellsprout", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿De qué tipo es Lapras?", "respuesta_1": "Agua y Hielo", "respuesta_2": "Solo Agua", "respuesta_3": "Agua y Dragón", "respuesta_4": "Agua y Normal", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon dragón'?", "respuesta_1": "Dragonite", "respuesta_2": "Gyarados", "respuesta_3": "Charizard", "respuesta_4": "Kingdra", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es el fósil del Helix?", "respuesta_1": "Omanyte", "respuesta_2": "Kabuto", "respuesta_3": "Aerodactyl", "respuesta_4": "Lapras", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es la evolución de Poliwhirl si usa una piedra agua?", "respuesta_1": "Poliwrath", "respuesta_2": "Politoed", "respuesta_3": "Slowbro", "respuesta_4": "Kingler", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon evoluciona a Machamp?", "respuesta_1": "Machoke", "respuesta_2": "Machop", "respuesta_3": "Hitmonchan", "respuesta_4": "Primeape", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon de tipo fuego puede aprender Surf?", "respuesta_1": "Charizard", "respuesta_2": "Arcanine", "respuesta_3": "Magmar", "respuesta_4": "Ninguno", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon clon'?", "respuesta_1": "Ditto", "respuesta_2": "Mewtwo", "respuesta_3": "Mew", "respuesta_4": "Jynx", "respuesta_correcta": 2},
    {"pregunta": "¿De qué tipo es Gyarados?", "respuesta_1": "Agua y Volador", "respuesta_2": "Agua y Dragón", "respuesta_3": "Solo Agua", "respuesta_4": "Dragón y Volador", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon evoluciona a Golem?", "respuesta_1": "Graveler", "respuesta_2": "Geodude", "respuesta_3": "Rhydon", "respuesta_4": "Onix", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon flor'?", "respuesta_1": "Vileplume", "respuesta_2": "Oddish", "respuesta_3": "Gloom", "respuesta_4": "Venusaur", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo lucha?", "respuesta_1": "Hitmonlee", "respuesta_2": "Machoke", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon puede aprender el ataque Explosión?", "respuesta_1": "Electrode", "respuesta_2": "Weezing", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon gas'?", "respuesta_1": "Gastly", "respuesta_2": "Weezing", "respuesta_3": "Koffing", "respuesta_4": "Muk", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon evoluciona usando una piedra trueno?", "respuesta_1": "Pikachu", "respuesta_2": "Magnemite", "respuesta_3": "Electabuzz", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es el Pokémon que tiene la habilidad Levitar?", "respuesta_1": "Gengar", "respuesta_2": "Weezing", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon de tipo hielo es conocido por su gran velocidad?", "respuesta_1": "Articuno", "respuesta_2": "Jynx", "respuesta_3": "Dewgong", "respuesta_4": "Cloyster", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon roca'?", "respuesta_1": "Geodude", "respuesta_2": "Onix", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Cuál es el Pokémon de tipo eléctrico que evoluciona a Raichu?", "respuesta_1": "Pikachu", "respuesta_2": "Magnemite", "respuesta_3": "Electabuzz", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon magma'?", "respuesta_1": "Magmar", "respuesta_2": "Charizard", "respuesta_3": "Flareon", "respuesta_4": "Arcanine", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon de tipo agua evoluciona a Blastoise?", "respuesta_1": "Wartortle", "respuesta_2": "Squirtle", "respuesta_3": "Golduck", "respuesta_4": "Seadra", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es el Pokémon de tipo roca que evoluciona a Rhydon?", "respuesta_1": "Geodude", "respuesta_2": "Graveler", "respuesta_3": "Rhyhorn", "respuesta_4": "Kabuto", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon huevo'?", "respuesta_1": "Chansey", "respuesta_2": "Exeggcute", "respuesta_3": "Togepi", "respuesta_4": "Blissey", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon puede aprender el ataque Psíquico?", "respuesta_1": "Alakazam", "respuesta_2": "Mr. Mime", "respuesta_3": "Hypno", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon es el último en la Pokédex de Kanto?", "respuesta_1": "Dragonite", "respuesta_2": "Articuno", "respuesta_3": "Mew", "respuesta_4": "Mewtwo", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon tiene un caparazón duro como su característica distintiva?", "respuesta_1": "Shellder", "respuesta_2": "Cloyster", "respuesta_3": "Omanyte", "respuesta_4": "Kabutops", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es la evolución de Growlithe si usa una piedra fuego?", "respuesta_1": "Arcanine", "respuesta_2": "Ninetales", "respuesta_3": "Flareon", "respuesta_4": "Rapidash", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon de tipo eléctrico tiene tres evoluciones?", "respuesta_1": "Pikachu", "respuesta_2": "Eevee", "respuesta_3": "Magnemite", "respuesta_4": "Jolteon", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon venenoso'?", "respuesta_1": "Ekans", "respuesta_2": "Koffing", "respuesta_3": "Nidoran♀", "respuesta_4": "Muk", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon puede aprender el movimiento 'Vuelo'?", "respuesta_1": "Pidgeotto", "respuesta_2": "Fearow", "respuesta_3": "Dodrio", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Cuál es la preevolución de Jigglypuff?", "respuesta_1": "Clefairy", "respuesta_2": "Wigglytuff", "respuesta_3": "Igglybuff", "respuesta_4": "No tiene", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon de tipo tierra evoluciona a Sandslash?", "respuesta_1": "Cubone", "respuesta_2": "Sandshrew", "respuesta_3": "Diglett", "respuesta_4": "Dugtrio", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon pato'?", "respuesta_1": "Farfetch’d", "respuesta_2": "Psyduck", "respuesta_3": "Golduck", "respuesta_4": "Poliwag", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon evoluciona al intercambiarlo?", "respuesta_1": "Kadabra", "respuesta_2": "Machoke", "respuesta_3": "Graveler", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon es conocido por usar ataques basados en sonido?", "respuesta_1": "Jigglypuff", "respuesta_2": "Mr. Mime", "respuesta_3": "Exeggutor", "respuesta_4": "Clefairy", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon evoluciona a Butterfree?", "respuesta_1": "Caterpie", "respuesta_2": "Weedle", "respuesta_3": "Metapod", "respuesta_4": "Beedrill", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon tiene tres cabezas?", "respuesta_1": "Dodrio", "respuesta_2": "Exeggutor", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Cuál es el único Pokémon legendario de tipo hielo?", "respuesta_1": "Zapdos", "respuesta_2": "Articuno", "respuesta_3": "Moltres", "respuesta_4": "Lapras", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon murciélago'?", "respuesta_1": "Zubat", "respuesta_2": "Golbat", "respuesta_3": "Crobat", "respuesta_4": "Ambos", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon puede aprender el ataque 'Rayo'? ", "respuesta_1": "Jolteon", "respuesta_2": "Zapdos", "respuesta_3": "Pikachu", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Cuál de estos Pokémon tiene tres evoluciones?", "respuesta_1": "Charmander", "respuesta_2": "Poliwag", "respuesta_3": "Abra", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon tiene la habilidad de duplicarse con el movimiento 'Doble Equipo'?", "respuesta_1": "Ditto", "respuesta_2": "Kadabra", "respuesta_3": "Pikachu", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon evoluciona con una Piedra Lunar?", "respuesta_1": "Jigglypuff", "respuesta_2": "Nidorina", "respuesta_3": "Clefairy", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Cuál es el Pokémon inicial de tipo agua en Kanto?", "respuesta_1": "Squirtle", "respuesta_2": "Psyduck", "respuesta_3": "Seel", "respuesta_4": "Poliwag", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon de tipo bicho tiene el ataque 'Picadura'? ", "respuesta_1": "Caterpie", "respuesta_2": "Weedle", "respuesta_3": "Paras", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon tiene una cola con una llama constante?", "respuesta_1": "Flareon", "respuesta_2": "Rapidash", "respuesta_3": "Charmander", "respuesta_4": "Magmar", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon evoluciona a Nidoking?", "respuesta_1": "Nidorino", "respuesta_2": "Nidoran♂", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon de tipo hielo se encuentra en la Cueva Celeste?", "respuesta_1": "Articuno", "respuesta_2": "Jynx", "respuesta_3": "Lapras", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál es la evolución de Dratini?", "respuesta_1": "Dragonair", "respuesta_2": "Dragonite", "respuesta_3": "Gyarados", "respuesta_4": "No evoluciona", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon usa un caparazón para protegerse?", "respuesta_1": "Omanyte", "respuesta_2": "Kabuto", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon flor'? ", "respuesta_1": "Bulbasaur", "respuesta_2": "Gloom", "respuesta_3": "Vileplume", "respuesta_4": "Bellosom", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon de electricidad'?", "respuesta_1": "Pikachu", "respuesta_2": "Electrode", "respuesta_3": "Magnemite", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Cuál de estos Pokémon evoluciona con amistad?", "respuesta_1": "Clefairy", "respuesta_2": "Eevee", "respuesta_3": "Jigglypuff", "respuesta_4": "Ninguno", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon de tipo fantasma está en la Torre Pokémon?", "respuesta_1": "Gastly", "respuesta_2": "Haunter", "respuesta_3": "Gengar", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon tiene un diseño similar a una Pokéball?", "respuesta_1": "Voltorb", "respuesta_2": "Electrode", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon tiene un movimiento exclusivo llamado 'Golpe Furia'?", "respuesta_1": "Farfetch'd", "respuesta_2": "Tauros", "respuesta_3": "Primeape", "respuesta_4": "Ambos", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál es el Pokémon con mayor velocidad base de Kanto?", "respuesta_1": "Jolteon", "respuesta_2": "Electrode", "respuesta_3": "Aerodactyl", "respuesta_4": "Mewtwo", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon se conoce como el 'Pokémon burbuja'?", "respuesta_1": "Squirtle", "respuesta_2": "Horsea", "respuesta_3": "Seadra", "respuesta_4": "Ambos", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon tiene una habilidad llamada 'Clorofila'?", "respuesta_1": "Oddish", "respuesta_2": "Bellsprout", "respuesta_3": "Vileplume", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Cuál de estos Pokémon no pertenece a la primera generación?", "respuesta_1": "Mewtwo", "respuesta_2": "Togepi", "respuesta_3": "Articuno", "respuesta_4": "Gyarados", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon Pato'? ", "respuesta_1": "Farfetch'd", "respuesta_2": "Golduck", "respuesta_3": "Psyduck", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon evoluciona a Poliwhirl?", "respuesta_1": "Poliwag", "respuesta_2": "Poliwrath", "respuesta_3": "Politoed", "respuesta_4": "Ninguno", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon tiene la habilidad especial 'Absorber Agua'?", "respuesta_1": "Vaporeon", "respuesta_2": "Lapras", "respuesta_3": "Omanyte", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon Imán'?", "respuesta_1": "Magnemite", "respuesta_2": "Magneton", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon se encuentra en la Mansión Pokémon?", "respuesta_1": "Ditto", "respuesta_2": "Grimer", "respuesta_3": "Magmar", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon venenoso'? ", "respuesta_1": "Grimer", "respuesta_2": "Muk", "respuesta_3": "Koffing", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon tiene el mayor nivel de ataque base de Kanto?", "respuesta_1": "Dragonite", "respuesta_2": "Mewtwo", "respuesta_3": "Rhydon", "respuesta_4": "Machamp", "respuesta_correcta": 2},
    {"pregunta": "¿Cuál de estos Pokémon evoluciona usando una piedra trueno?", "respuesta_1": "Eevee", "respuesta_2": "Pikachu", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon Llama'? ", "respuesta_1": "Charizard", "respuesta_2": "Rapidash", "respuesta_3": "Magmar", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon tiene un caparazón espinoso?", "respuesta_1": "Cloyster", "respuesta_2": "Kabutops", "respuesta_3": "Omastar", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon Pegajoso'?", "respuesta_1": "Grimer", "respuesta_2": "Muk", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon evoluciona a Gengar?", "respuesta_1": "Haunter", "respuesta_2": "Gastly", "respuesta_3": "Ninguno", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon aparece como fantasma en la Torre Pokémon?", "respuesta_1": "Gastly", "respuesta_2": "Haunter", "respuesta_3": "Marowak", "respuesta_4": "Cubone", "respuesta_correcta": 3},
    {"pregunta": "¿Cuál de estos Pokémon solo aparece pescando?", "respuesta_1": "Horsea", "respuesta_2": "Magikarp", "respuesta_3": "Shellder", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon evoluciona con una Piedra Fuego?", "respuesta_1": "Growlithe", "respuesta_2": "Vulpix", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon es el más pesado de la primera generación?", "respuesta_1": "Snorlax", "respuesta_2": "Golem", "respuesta_3": "Onix", "respuesta_4": "Lapras", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon bola'?", "respuesta_1": "Electrode", "respuesta_2": "Voltorb", "respuesta_3": "Ambos", "respuesta_4": "Ninguno", "respuesta_correcta": 3},
    {"pregunta": "¿Qué Pokémon tiene una lengua extra larga?", "respuesta_1": "Lickitung", "respuesta_2": "Slowpoke", "respuesta_3": "Hypno", "respuesta_4": "Ninguno", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon de tipo roca evoluciona a Golem?", "respuesta_1": "Graveler", "respuesta_2": "Geodude", "respuesta_3": "Rhyhorn", "respuesta_4": "Ninguno", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon Semilla'? ", "respuesta_1": "Bulbasaur", "respuesta_2": "Ivysaur", "respuesta_3": "Vileplume", "respuesta_4": "Exeggutor", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo volador?", "respuesta_1": "Zubat", "respuesta_2": "Pidgey", "respuesta_3": "Magnemite", "respuesta_4": "Onix", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon evoluciona a Charizard?", "respuesta_1": "Charmeleon", "respuesta_2": "Charmander", "respuesta_3": "Squirtle", "respuesta_4": "Pidgey", "respuesta_correcta": 1},
    {"pregunta": "¿Cuál de estos Pokémon es de tipo veneno/agua?", "respuesta_1": "Horsea", "respuesta_2": "Poliwag", "respuesta_3": "Shellder", "respuesta_4": "Magikarp", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon tiene un cuerno en su cabeza?", "respuesta_1": "Kabuto", "respuesta_2": "Rhyhorn", "respuesta_3": "Paras", "respuesta_4": "Omanyte", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon evoluciona a Raichu?", "respuesta_1": "Pikachu", "respuesta_2": "Electrode", "respuesta_3": "Magnemite", "respuesta_4": "Voltorb", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido por tener una cola de fuego?", "respuesta_1": "Vulpix", "respuesta_2": "Charizard", "respuesta_3": "Magmar", "respuesta_4": "All", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon de tipo agua evoluciona a Blastoise?", "respuesta_1": "Wartortle", "respuesta_2": "Squirtle", "respuesta_3": "Seadra", "respuesta_4": "Psyduck", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon se encuentra en el Lago de la ira?", "respuesta_1": "Gyarados", "respuesta_2": "Magikarp", "respuesta_3": "Lapras", "respuesta_4": "Omanyte", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon grifo'?", "respuesta_1": "Griffon", "respuesta_2": "Articuno", "respuesta_3": "Pidgeot", "respuesta_4": "Zapdos", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es el primero en la Pokédex Nacional?", "respuesta_1": "Bulbasaur", "respuesta_2": "Pikachu", "respuesta_3": "Rhydon", "respuesta_4": "Magikarp", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon tiene la forma más pequeña de la Pokédex?", "respuesta_1": "Jigglypuff", "respuesta_2": "Squirtle", "respuesta_3": "Zubat", "respuesta_4": "Caterpie", "respuesta_correcta": 4},
    {"pregunta": "¿Cuántos Pokémon hay en total en la Pokédex de Kanto?", "respuesta_1": "150", "respuesta_2": "151", "respuesta_3": "152", "respuesta_4": "154", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon tiene la capacidad de volverse invisible?", "respuesta_1": "Ditto", "respuesta_2": "Abra", "respuesta_3": "Kadabra", "respuesta_4": "Pikachu", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon puede aprender el movimiento 'Psíquico'?", "respuesta_1": "Mewtwo", "respuesta_2": "Abra", "respuesta_3": "Psyduck", "respuesta_4": "Todos los anteriores", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon ráfaga'? ", "respuesta_1": "Zapdos", "respuesta_2": "Pidgeot", "respuesta_3": "Articuno", "respuesta_4": "Aerodactyl", "respuesta_correcta": 1},
    {"pregunta": "¿Qué Pokémon es conocido como el 'Pokémon cadena'? ", "respuesta_1": "Kabuto", "respuesta_2": "Magikarp", "respuesta_3": "Onix", "respuesta_4": "Caterpie", "respuesta_correcta": 4},
    {"pregunta": "¿Qué Pokémon se usa para obtener la MO1 Corte?", "respuesta_1": "Paras", "respuesta_2": "Exeggutor", "respuesta_3": "Pidgey", "respuesta_4": "Bulbasaur", "respuesta_correcta": 1},
    {"pregunta": "¿Quién es el líder de gimnasio de Ciudad Celeste?", "respuesta_1": "Brock", "respuesta_2": "Misty", "respuesta_3": "Giovanni", "respuesta_4": "Erika", "respuesta_correcta": 2},
    {"pregunta": "¿Qué Pokémon evoluciona a Dugtrio?", "respuesta_1": "Diglett", "respuesta_2": "Rhyhorn", "respuesta_3": "Geodude", "respuesta_4": "Nidoran", "respuesta_correcta": 1}
]